apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: aws code pipeline actions
inputs:
  pipeline-name:  # id of input
    description: 'pipeline name'
    required: true
  parameters:  # id of input
    description: 'parameters'
    required: false
    default: '{}'
      
runs:
  using: composite
  steps:
    - id: invoke-aws-code-pipeline-job
      name: invoke-aws-code-pipeline-job
      uses: docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/aws-codepipeline-invoke-actions:main-bc66a6cc3102888819a063f0db4e027ad724b89d
      shell: sh
      env:
        CONFIG_JSON: '{"metaInfo":{"action":"AWS_CODEPIPELINE_ACTIONS","pipelineName":"${{ inputs.pipeline-name }}","parameters":${{ inputs.parameters }}}}'
        RUN_ID: ${{ cloudbees.run_id }}
        JOB_ID: ${{ job.id }}
        STEP_ID: ${{ step.internal.id }}
        DNS_URL: ${{ cloudbees.api.url }}
        JWT_TOKEN: ${{ cloudbees.api.token }}
      run: |
        set -x
        cd /app
        ./aws_codepipeline_actions_app invoke -i $CONFIG_JSON
